### ISSUE TITLE
AttributeError: module 'marshmallow.fields' has no attribute 'FormattedString'

### ISSUE THREAD

**Issue by scopalaffairs** [briancappello/flask-unchained-react-spa#12]
Hello,

I love the concept and plan to migrate from your older boilerplate architecture towards the unchained-paradigma.
After a fresh cloned install via docker-compose, I currently run into this error message.

`backend_1        | Traceback (most recent call last):
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/cli.py", line 56, in cli_create_app
backend_1        |     return AppFactory.create_app(env)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/app_factory.py", line 55, in create_app
backend_1        |     bundles or getattr(unchained_config, 'BUNDLES', []))
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/app_factory.py", line 143, in _load_bundles
backend_1        |     bundle = _load_bundle(bundle_package_name, _is_bundle)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/app_factory.py", line 154, in _load_bundle
backend_1        |     module = importlib.import_module(module_name)
backend_1        |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
backend_1        |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1        |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
backend_1        |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
backend_1        |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
backend_1        |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend_1        |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
backend_1        |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
backend_1        |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
backend_1        |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
backend_1        |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
backend_1        |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/admin/__init__.py", line 4, in <module>
backend_1        |     from .model_admin import ModelAdmin
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/admin/model_admin.py", line 9, in <module>
backend_1        |     from .security import AdminSecurityMixin
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/admin/security.py", line 5, in <module>
backend_1        |     from flask_unchained.bundles.security import current_user as user
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/security/__init__.py", line 8, in <module>
backend_1        |     from .views import SecurityController, UserResource
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/security/views/__init__.py", line 2, in <module>
backend_1        |     from .user_resource import UserResource
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/security/views/user_resource.py", line 2, in <module>
backend_1        |     from flask_unchained.bundles.api import ModelResource
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/api/__init__.py", line 6, in <module>
backend_1        |     from .extensions import Api, Marshmallow, api, ma
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/api/extensions/__init__.py", line 6, in <module>
backend_1        |     ma = Marshmallow()
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/api/extensions/marshmallow.py", line 46, in __init__
backend_1        |     self.FormattedString = ma.fields.FormattedString
backend_1        | AttributeError: module 'marshmallow.fields' has no attribute 'FormattedString'`

Can you concur with this message?

**Comment by briancappello** [comment]
Hey @scopalaffairs, thanks for the report!

I've pushed up a commit to master that should hopefully fix docker for you - the problem is that I haven't been able to get Flask Unchained v0.8 released yet, while master of this repository will only work with the master branch of Flask Unchained. So for now, I updated the `requirements.txt` file to install Flask Unchained from master. There might be other bugs lurking, I don't do development with docker myself :/
