### ISSUE TITLE
backend: ImportError: cannot import name 'BundleConfig

### ISSUE THREAD

**Issue by achiang** [briancappello/flask-unchained-react-spa#3]
After running `docker-compose up --build`, the backend container seems to be in a crash loop.

```
backend_1        | Traceback (most recent call last):
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/cli.py", line 56, in cli_create_app
backend_1        |     return AppFactory.create_app(env)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/app_factory.py", line 75, in create_app
backend_1        |     unchained.init_app(app, env, bundles, _config_overrides=_config_overrides)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/unchained.py", line 167, in init_app
backend_1        |     run_hooks_hook.run_hook(app, bundles, _config_overrides=_config_overrides)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/hooks/run_hooks_hook.py", line 31, in run_hook
backend_1        |     hook.run_hook(app, bundles, _config_overrides=_config_overrides)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/hooks/configure_app_hook.py", line 51, in run_hook
backend_1        |     bundle_config = self.get_config(bundle, app.env)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/hooks/configure_app_hook.py", line 72, in get_config
backend_1        |     bundle_config_module = self.import_bundle_module(bundle)
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/app_factory_hook.py", line 188, in import_bundle_module
backend_1        |     return safe_import_module(self.get_module_name(bundle))
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/utils.py", line 100, in safe_import_module
backend_1        |     raise e
backend_1        |   File "/usr/local/lib/python3.6/site-packages/flask_unchained/utils.py", line 97, in safe_import_module
backend_1        |     return import_module(module_name)
backend_1        |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
backend_1        |     return _bootstrap._gcd_import(name[level:], package, level)
backend_1        |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
backend_1        |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
backend_1        |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
backend_1        |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
backend_1        |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
backend_1        |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
backend_1        |   File "/flask/src/bundles/blog/config.py", line 3, in <module>
backend_1        |     from flask_unchained import BundleConfig
backend_1        | ImportError: cannot import name 'BundleConfig'
backend_1        | 
backend_1        | Waiting for postgres ready...
```

See this error repeated over and over.

Running with this version:

```
 git rev-parse HEAD
4c54faddde181ddf9d258a8b650b81cbaa340e6e
```

**Comment by achiang** [comment]
This super hacky patch will work around the problem enough to at least get all the main containers up and running.

```patch
diff --git a/docker/backend/Dockerfile b/docker/backend/Dockerfile
index 48eeaee..b23c6c2 100644
--- a/docker/backend/Dockerfile
+++ b/docker/backend/Dockerfile
@@ -5,7 +5,7 @@ ENV PYTHONUNBUFFERED 1
 RUN apk add --no-cache shadow
 RUN useradd --user-group --create-home --home-dir /flask --shell /bin/false flask
 
-RUN apk add --no-cache linux-headers make gcc musl-dev libxml2-dev libxslt-dev libffi-dev postgresql-dev
+RUN apk add --no-cache linux-headers make gcc musl-dev libxml2-dev libxslt-dev libffi-dev postgresql-dev git
 
 WORKDIR /flask/src
 
diff --git a/requirements.txt b/requirements.txt
index d35f6c8..1bef923 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -4,7 +4,7 @@
 #
 #    pip-compile --output-file requirements.txt requirements.in
 #
-alembic==1.0.0            # via flask-migrate, sqlalchemy-unchained
+alembic==1.0.1            # via flask-migrate, sqlalchemy-unchained
 amqp==2.3.2               # via kombu
 apispec==0.39.0           # via flask-unchained
 appdirs==1.4.3
@@ -27,12 +27,14 @@ flask-marshmallow==0.9.0  # via flask-unchained
 flask-migrate==2.2.1      # via flask-unchained
 flask-principal==0.4.0    # via flask-unchained
 flask-session==0.3.1      # via flask-unchained
-flask-sqlalchemy-unchained==0.3.1  # via flask-unchained
+flask-sqlalchemy-unchained==0.7.0  # via flask-unchained
 flask-sqlalchemy==2.3.2   # via flask-migrate, flask-sqlalchemy-unchained
-flask-unchained[admin,api,celery,mail,security,session,sqlalchemy]==0.6.6
+git+git://github.com/briancappello/flask-unchained@12788a6#egg=flask-unchained
 flask-wtf==0.14.2         # via flask-unchained
 flask==1.0.2
-itsdangerous==0.24        # via flask, flask-unchained
+graphene==2.1.3
+graphene-sqlalchemy==2.1.0
+itsdangerous==1.1.0       # via flask, flask-unchained
 jinja2-time==0.2.0
 jinja2==2.10
 kombu==4.2.1              # via celery
@@ -40,13 +42,13 @@ lxml==4.2.5               # via flask-unchained
 mako==1.0.7               # via alembic
 markdown==3.0.1
 markupsafe==1.0           # via jinja2, mako
-marshmallow-sqlalchemy==0.14.1  # via flask-unchained
-marshmallow==2.16.0       # via flask-marshmallow, flask-unchained, marshmallow-sqlalchemy
+marshmallow-sqlalchemy==0.15.0  # via flask-unchained
+marshmallow==2.16.1       # via flask-marshmallow, flask-unchained, marshmallow-sqlalchemy
 networkx==2.2             # via flask-unchained
 passlib==1.7.1            # via flask-unchained
 psycopg2==2.7.5
-py-meta-utils==0.3.0      # via flask-unchained, sqlalchemy-unchained
-py-yaml-fixtures==0.2.0   # via flask-unchained
+py-meta-utils==0.7.4      # via flask-unchained, sqlalchemy-unchained
+py-yaml-fixtures==0.4.0   # via flask-unchained
 pycparser==2.19           # via cffi
 python-dateutil==2.7.3
 python-editor==1.0.3      # via alembic
@@ -56,7 +58,7 @@ pyyaml==3.13              # via apispec, py-yaml-fixtures, python-frontmatter
 redis==2.10.6
 six==1.11.0               # via bcrypt, faker, flask-marshmallow, python-dateutil, python-frontmatter
 speaklater==1.3           # via flask-babelex
-sqlalchemy-unchained==0.4.0  # via flask-sqlalchemy-unchained
+sqlalchemy-unchained==0.7.0  # via flask-sqlalchemy-unchained
 sqlalchemy==1.2.12        # via alembic, flask-sqlalchemy, marshmallow-sqlalchemy, sqlalchemy-unchained
 text-unidecode==1.2       # via faker
 tzlocal==1.5.1
```

The celery containers are still encountering errors:

```
celery_beat_1    | Traceback (most recent call last):
celery_beat_1    |   File "/usr/local/bin/celery", line 11, in <module>
celery_beat_1    |     sys.exit(main())
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
celery_beat_1    |     _main()
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
celery_beat_1    |     cmd.execute_from_commandline(argv)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
celery_beat_1    |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 273, in execute_from_commandline
celery_beat_1    |     argv = self.setup_app_from_commandline(argv)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
celery_beat_1    |     self.app = self.find_app(app)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 501, in find_app
celery_beat_1    |     return find_app(app, symbol_by_name=self.symbol_by_name)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 362, in find_app
celery_beat_1    |     sym = imp(app)
celery_beat_1    |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 104, in import_from_cwd
celery_beat_1    |     return imp(module, package=package)
celery_beat_1    |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery_beat_1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery_beat_1    |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
celery_beat_1    |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
celery_beat_1    |   File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
celery_beat_1    | ModuleNotFoundError: No module named 'wsgi.celery'; 'wsgi' is not a package
flask-unchained-react-spa_celery_beat_1 exited with code 1
```

**Comment by briancappello** [comment]
Hey @achiang, thanks for the bug reports! Hopefully I should have some time tonight or tomorrow to look into things more closely :)

**Comment by achiang** [comment]
@briancappello sounds good. I linked a bug in `flask-unchained` that seems like it's the root cause, which is simply that you need to make a new release, and bump the version in this project's requirements. :)

**Comment by achiang** [comment]
Pulled your latest branch, and everything looks great.

Thanks!
