### ISSUE TITLE
TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by Pymancer** [briancappello/flask-unchained-react-spa#8]
Error in `docker-compose up` console log:
```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask_unchained/cli.py", line 56, in cli_create_app
    return AppFactory.create_app(env)
  File "/usr/local/lib/python3.6/site-packages/flask_unchained/app_factory.py", line 75, in create_app
    unchained.init_app(app, env, bundles, _config_overrides=_config_overrides)
  File "/usr/local/lib/python3.6/site-packages/flask_unchained/unchained.py", line 109, in init_app
    run_hooks_hook.run_hook(app, bundles, _config_overrides=_config_overrides)
  File "/usr/local/lib/python3.6/site-packages/flask_unchained/hooks/run_hooks_hook.py", line 33, in run_hook
    hook.run_hook(app, bundles)
  File "/usr/local/lib/python3.6/site-packages/flask_unchained/app_factory_hook.py", line 98, in run_hook
    self.process_objects(app, self.collect_from_bundles(bundles))
  File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/sqlalchemy/hooks/register_models_hook.py", line 27, in process_objects
    self.bundle.models = UnchainedModelRegistry().finalize_mappings()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy_unchained/model_registry.py", line 73, in finalize_mappings
    if self.should_initialize(self._models[name]):
  File "/usr/local/lib/python3.6/site-packages/flask_unchained/bundles/sqlalchemy/model_registry.py", line 43, in should_initialize
    if model_name in self._initialized:
TypeError: unhashable type: 'dict'
```

**Comment by briancappello** [comment]
Hey, sorry you ran into this! The master branch of this repo is in a bit of a weird state at the moment, because it's targeting the master branch of Flask Unchained. Strangely I couldn't get the docker files to work when I tried to install Flask Unchained from master there. I'm working on getting the next version of Flask Unchained released, but I still have some work to do, mainly on the docs. In the meantime, you can checkout commit hash `c0b94f3b608d95a349c6fe9b7a99a40c89da42c9` of this repo and that should work:

```
git checkout c0b94f3b608d95a349c6fe9b7a99a40c89da42c9
```

I also had to configure the timezone in `docker/backend/Dockerfile`:

```diff
-RUN apk add --no-cache linux-headers make gcc musl-dev libxml2-dev libxslt-dev libffi-dev postgresql postgresql-dev
+RUN apk add --no-cache linux-headers make gcc musl-dev libxml2-dev libxslt-dev libffi-dev postgresql postgresql-dev tzdata
+RUN cp /usr/share/zoneinfo/UTC /etc/localtime
+RUN echo "UTC" > /etc/timezone
```

**Comment by Pymancer** [comment]
> I'm working on getting the next version of Flask Unchained released

I'll wait, thx)
